name: Static Analysis

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'composer*'
      - 'psalm*'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer dependencies
        run: "composer update --no-interaction --no-progress --no-scripts --prefer-dist"

      - name: Run Psalm
        run: ./vendor/bin/psalm --find-unused-psalm-suppress --output-format=github --shepherd

      - name: Run Psalm
        run: ./vendor/bin/psalm --find-unused-psalm-suppress --output-format=github --shepherd
        env:
          PSALM_SHEPHERD_HOST: shepherd.dev

      - name: Run Psalm (default, no value)
        run: ./vendor/bin/psalm --find-unused-psalm-suppress --output-format=github --shepherd
        env:
          PSALM_SHEPHERD_HOST: custom-domain.shepherd

      - name: Run Psalm (shepherd.dev)
        run: ./vendor/bin/psalm --find-unused-psalm-suppress --output-format=github --shepherd=shepherd.dev

      - name: Run Psalm (https://shepherd.dev)
        run: ./vendor/bin/psalm --find-unused-psalm-suppress --output-format=github --shepherd=https://shepherd.dev

      - name: Run Psalm (custom endpoint with hash)
        run: ./vendor/bin/psalm --find-unused-psalm-suppress --output-format=github --shepherd=https://shepherd.dev/hooks/psalm#
