name: Static Analysis

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'composer*'
      - 'psalm*'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer dependencies
        run: "composer update --no-interaction --no-progress --no-scripts"

      - name: Run Psalm
        run: ./vendor/bin/psalm --find-unused-psalm-suppress --output-format=github --shepherd
